<?php

// This file is part of Pollaris.
// Copyright 2024 Marien Fressinaud
// SPDX-License-Identifier: AGPL-3.0-or-later

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

// phpcs:disable Generic.Files.LineLength
final class Version20240823073742CreateVoteAndAnswer extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the vote and answer tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE answer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, value VARCHAR(10) NOT NULL, vote_id VARCHAR(20) NOT NULL, proposal_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_DADD4A2572DCDAFC ON answer (vote_id)');
        $this->addSql('CREATE INDEX IDX_DADD4A25F4792058 ON answer (proposal_id)');

        $this->addSql('CREATE TABLE vote (id VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, author_name VARCHAR(100) NOT NULL, poll_id VARCHAR(20) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5A1085643C947C0F ON vote (poll_id)');

        $this->addSql('ALTER TABLE answer ADD CONSTRAINT FK_DADD4A2572DCDAFC FOREIGN KEY (vote_id) REFERENCES vote (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE answer ADD CONSTRAINT FK_DADD4A25F4792058 FOREIGN KEY (proposal_id) REFERENCES proposal (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vote ADD CONSTRAINT FK_5A1085643C947C0F FOREIGN KEY (poll_id) REFERENCES poll (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE answer DROP CONSTRAINT FK_DADD4A2572DCDAFC');
        $this->addSql('ALTER TABLE answer DROP CONSTRAINT FK_DADD4A25F4792058');
        $this->addSql('ALTER TABLE vote DROP CONSTRAINT FK_5A1085643C947C0F');
        $this->addSql('DROP TABLE answer');
        $this->addSql('DROP TABLE vote');
    }
}
