<?php

// This file is part of Pollaris.
// Copyright 2024-2025 Marien Fressinaud
// SPDX-License-Identifier: AGPL-3.0-or-later

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

// phpcs:disable Generic.Files.LineLength
final class Version20241030163352CreateDate extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the date table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE date (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, value TIMESTAMP(0) WITH TIME ZONE NOT NULL, poll_id VARCHAR(20) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_AA9E377A3C947C0F ON date (poll_id)');
        $this->addSql('ALTER TABLE date ADD CONSTRAINT FK_AA9E377A3C947C0F FOREIGN KEY (poll_id) REFERENCES poll (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE date DROP CONSTRAINT FK_AA9E377A3C947C0F');
        $this->addSql('DROP TABLE date');
    }
}
